##
# @author Thanos Tourikas
##

version: '2'
services:

  ## VIRTUOSO SERVICE
  virtuoso:
    image: tourikas/virtuoso:2017-07-17T1338
    volumes:
#      - /home/ato/Devel/deploy/app/contreg/virtuoso:/data
#      - /home/ato/Devel/deploy/app/contreg:/contreg
      - virtuoso:/data
      - contreg:/contreg
    ports:
      - "1111:1111"

  ## CONTREG SERVICE
  contreg:
    image: tourikas/contreg:2017-07-17T1505
    env_file: docker.env
#    ports:
#      - "8080:8080"
    links:
      - virtuoso
#    volumes_from:
#      - virtuoso
    volumes:
#      - /home/ato/Devel/deploy/app/contreg:/contreg
      - contreg:/contreg