##
# @author George Sofianos
##

version: '2'
services:

  ## VIRTUOSO SERVICE
  virtuoso:
    image: sofiageo/virtuoso:2017-09-21T1334
    volumes:
      - virtuoso:/data
      - contreg:/opt/contreg

  ## CONTREG SERVICE
  contreg:
    image: sofiageo/contreg:2017-09-21T1252
    env_file: docker.env
    links:
      - virtuoso
    volumes:
      - contreg:/opt/contreg